[default.extend-words]
enew = "enew"
noice = "noice"
# `seperator` should be `separator`
seperator = "seperator"
# `hightlight` should be `highlight`
hightlight = "hightlight"

[files]
extend-exclude = [
]
